[simulation]
jd = 2459921.01
dt = 0.1
qtarget = [1.0, 0.0, 0.0, 0.0]  # Quaternion as a list of coefficients
w = [0.0, 0.0, 0.0]

[controller]
kp = 0.2
kd = 1.0

[gravity]
model = "EGM2008"
n_max_dP = 1

[orbit]
semi_major_axis = 522863.7
eccentricity = 0.01
inclination = 98.0
RAAN = 306.615
argument_of_perigee = 314.19
mean_anomaly = 99.89