name = "ADCSSims"
uuid = "ee4cf526-cd8e-4de0-b4eb-cb39a21bf5aa"
authors = ["Orestis Ousoultzoglou <orousoultzoglou@gmail.com>", "Romanos Voulgarakis <voulgarakisromanos@gmail.com>", "and contributors"]
version = "0.0.1-DEV"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SatelliteDynamics = "0e7c1a32-1b9f-5532-88a4-e668712d6a4c"
SatelliteToolbox = "6ac157d9-b43d-51bb-8fab-48bf53814f4a"
SatelliteToolboxGeomagneticField = "9fc549ba-b5d7-49a2-b268-8171e5fb6e89"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
SatelliteToolboxGeomagneticField = "0.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
